name: "CI Reports"
run-name: "CI Reports"

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

env:
  DOWNLOAD_ARTIFACTS_PATH: ./github/artifacts

jobs:
  test_report:
    name: Create test report
    runs-on: ubuntu-latest
    steps:
    -
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: JEST Tests
        path: '*.xml'
        reporter: java-junit
  test_coverage_report:
    name: Create test coverage report
    runs-on: ubuntu-latest
    steps:
      -
        name: Download Artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: test-coverage-results
          path: ${{ env.DOWNLOAD_ARTIFACTS_PATH }}/coverage-results
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ${{ env.DOWNLOAD_ARTIFACTS_PATH }}/coverage-results/common.xml
          format: markdown
          output: both
          badge: true
          fail_below_min: true
          hide_complexity: true
          indicators: true
          thresholds: '60 80'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event.workflow_run.event == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
          number: ${{ github.event.workflow_run.pull_requests[0].number }}